# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memory_pb2 as nylon_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nylon/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryEngineStub:
    """尼龙记忆引擎 gRPC 契约（对应《尼龙技术架构设计》2.2 节）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Weave = channel.unary_unary(
                '/nylon.v1.MemoryEngine/Weave',
                request_serializer=nylon_dot_v1_dot_memory__pb2.WeaveRequest.SerializeToString,
                response_deserializer=nylon_dot_v1_dot_memory__pb2.WeaveResponse.FromString,
                _registered_method=True)
        self.WeaveSession = channel.unary_unary(
                '/nylon.v1.MemoryEngine/WeaveSession',
                request_serializer=nylon_dot_v1_dot_memory__pb2.WeaveSessionRequest.SerializeToString,
                response_deserializer=nylon_dot_v1_dot_memory__pb2.WeaveSessionResponse.FromString,
                _registered_method=True)
        self.Resonate = channel.unary_unary(
                '/nylon.v1.MemoryEngine/Resonate',
                request_serializer=nylon_dot_v1_dot_memory__pb2.ResonateRequest.SerializeToString,
                response_deserializer=nylon_dot_v1_dot_memory__pb2.ResonateResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/nylon.v1.MemoryEngine/Search',
                request_serializer=nylon_dot_v1_dot_memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=nylon_dot_v1_dot_memory__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/nylon.v1.MemoryEngine/GetNode',
                request_serializer=nylon_dot_v1_dot_memory__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=nylon_dot_v1_dot_memory__pb2.GetNodeResponse.FromString,
                _registered_method=True)


class MemoryEngineServicer:
    """尼龙记忆引擎 gRPC 契约（对应《尼龙技术架构设计》2.2 节）
    """

    def Weave(self, request, context):
        """记忆编织：原始事件 → 多丝分解 → 建边 → 冲突检测 → 入库
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WeaveSession(self, request, context):
        """双层写入编织：整段 session 批量入库（叶子层=逐事件原文）+ 引擎侧 LLM 抽象事实层
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resonate(self, request, context):
        """情境共振：种子 + 情境 → 共振记忆簇（优先级队列 + 全局激活预算）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """向量检索：Top-K 近邻
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """读取单节点（含实时张力）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Weave': grpc.unary_unary_rpc_method_handler(
                    servicer.Weave,
                    request_deserializer=nylon_dot_v1_dot_memory__pb2.WeaveRequest.FromString,
                    response_serializer=nylon_dot_v1_dot_memory__pb2.WeaveResponse.SerializeToString,
            ),
            'WeaveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.WeaveSession,
                    request_deserializer=nylon_dot_v1_dot_memory__pb2.WeaveSessionRequest.FromString,
                    response_serializer=nylon_dot_v1_dot_memory__pb2.WeaveSessionResponse.SerializeToString,
            ),
            'Resonate': grpc.unary_unary_rpc_method_handler(
                    servicer.Resonate,
                    request_deserializer=nylon_dot_v1_dot_memory__pb2.ResonateRequest.FromString,
                    response_serializer=nylon_dot_v1_dot_memory__pb2.ResonateResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=nylon_dot_v1_dot_memory__pb2.SearchRequest.FromString,
                    response_serializer=nylon_dot_v1_dot_memory__pb2.SearchResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=nylon_dot_v1_dot_memory__pb2.GetNodeRequest.FromString,
                    response_serializer=nylon_dot_v1_dot_memory__pb2.GetNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nylon.v1.MemoryEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nylon.v1.MemoryEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryEngine:
    """尼龙记忆引擎 gRPC 契约（对应《尼龙技术架构设计》2.2 节）
    """

    @staticmethod
    def Weave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nylon.v1.MemoryEngine/Weave',
            nylon_dot_v1_dot_memory__pb2.WeaveRequest.SerializeToString,
            nylon_dot_v1_dot_memory__pb2.WeaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WeaveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nylon.v1.MemoryEngine/WeaveSession',
            nylon_dot_v1_dot_memory__pb2.WeaveSessionRequest.SerializeToString,
            nylon_dot_v1_dot_memory__pb2.WeaveSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resonate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nylon.v1.MemoryEngine/Resonate',
            nylon_dot_v1_dot_memory__pb2.ResonateRequest.SerializeToString,
            nylon_dot_v1_dot_memory__pb2.ResonateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nylon.v1.MemoryEngine/Search',
            nylon_dot_v1_dot_memory__pb2.SearchRequest.SerializeToString,
            nylon_dot_v1_dot_memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nylon.v1.MemoryEngine/GetNode',
            nylon_dot_v1_dot_memory__pb2.GetNodeRequest.SerializeToString,
            nylon_dot_v1_dot_memory__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
